- name: Mac Setup
  hosts: all
  connection: local

  vars:
    dotfiles_repo: "https://github.com/kotapiku/dotfiles.git"

  tasks:
    - name: Make sure dotfiles are present
      git:
        repo: "{{ dotfiles_repo }}"
        dest: ~/dotfiles

  roles:
    - {role: homebrew, tags: 'brew'}
    - {role: osx_defaults, tags: 'osx'}
    # - {role: mas, tags: 'mas'}
