- name: brew tap
  homebrew_tap:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_taps }}"

- name: brew cask install
  homebrew_cask:
    name: "{{ item }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: brew update
  homebrew:
    update_homebrew: yes

- name: brew install
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"
