- name: brew tap
  homebrew_tap:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_taps }}"

- name: brew install --cask
  homebrew_cask:
    name: "{{ item }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: brew update
  homebrew:
    update_homebrew: yes

- name: brew install
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"

- name: brew install universal_ctags
  homebrew:
    name: "universal-ctags/universal-ctags/universal-ctags"
    install_options: "HEAD"
    state: "present"
