- name: System Preferences
  osx_defaults:
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value | default() }}"
  with_items:
    - "{{ apple_defaults }}"

- name: System Preferences (com)
  osx_defaults:
    host: "{{ item.host | default() }}"
    domain: "com.apple.{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value | default() }}"
  with_items:
    - "{{ apple_defaults_com }}"
